Add members' and projects' page
IMGIITRoorkee/omniport-frontend-maintainer-site pull request #36
Opened 2023-05-06 12:32 UTC by bbahd30

2023-05-09 13:25 UTC, nikkuAg commented on src/components/alumni/alumni-page.js
Either use class-based or functional based everywhere

2023-05-10 11:15 UTC, nikkuAg requested changes
Try to use only one kind of components either Class based or Functional based

2023-05-10 11:15 UTC, nikkuAg commented on src/components/app.js
> +        <div div styleName="blocks.container">
extra div kyu likha?

2023-05-10 11:15 UTC, nikkuAg commented on src/components/blog/blog-post-card.js
> +                    <div className="time">5 min read</div>
Time hard code krna ha ya baad mai change kroge

2023-05-10 11:15 UTC, nikkuAg commented on src/components/header/app-header-browser-grid.js
> +            <NavLink /* to={`${urlAppMember()}`} */ to={`${urlAppBase()}`} activeStyle={ACTIVE_STYLE.culture} >
Comment hta de

2023-05-10 11:15 UTC, nikkuAg commented on src/components/main/sections/blog/blog-section.js
Why class-based component, if all other are functional based

2023-05-10 11:15 UTC, nikkuAg commented on src/components/main/sections/info/info-section.js
> +      {/* <hr /> */}
Remove comment

2023-05-10 11:15 UTC, nikkuAg commented on src/components/main/sections/project/project-grid-layout.js
Either class based or functional based

2023-05-10 11:15 UTC, nikkuAg commented on src/components/member-individual-view.js
> +            <ProjectDetail /* key={index} */ info={info} key={info.slug} />
remove comment

2023-05-10 11:15 UTC, nikkuAg commented on src/components/member-individual-view.js
> +                    {/* <div styleName="styles.role-designation">
Remove comment

2023-05-10 11:15 UTC, nikkuAg commented on src/components/team/member-card.js
> +                <Link to={"../" + member + "/" + info.informalHandle}>
Use the format option `${member}`

2023-05-10 11:15 UTC, nikkuAg commented on src/components/team/member-page.js
> +                        // linkOptions={linkOptions}
Remove comment

2023-05-10 11:15 UTC, nikkuAg commented on src/css/blog/blog-post-card.css
> +    /* width: fit-content; */
remove comment

2023-05-10 11:15 UTC, nikkuAg commented on src/css/blog/blog-section.css
> +.verticalCategory > *{
why > *

2023-05-10 11:15 UTC, nikkuAg commented on src/css/blog/blog-section.css
> +.verticalCategory > * > div:first-child{
provide a new class

2023-05-10 11:15 UTC, nikkuAg commented on src/css/blog/blog-section.css
> +}
Add a new line at end

2023-05-10 11:15 UTC, nikkuAg commented on src/css/footer/app-footer.css
> +}
New line at end

2023-05-10 11:15 UTC, nikkuAg commented on src/css/sections/info/info-section.css
> +}
New line at end of file

2023-05-10 11:15 UTC, nikkuAg commented on src/css/sections/project/project-grid-layout.css
>  }
New line at end of file

2023-05-10 11:15 UTC, nikkuAg commented on src/css/utilComponents/toggleBtn.css
> +}
New line at end of file

2023-05-10 11:15 UTC, nikkuAg requested changes
Try to use only one kind of components either Class based or Functional based

2023-05-10 13:43 UTC, bbahd30 commented on src/components/blog/blog-post-card.js
> +                    <div className="time">5 min read</div>
Abhi time ki info api me nhi hai..so alag se api likhni hai iski

2023-05-22 15:52 UTC, sweety-sg commented on src/components/member-individual-view.js
> +                  style={{
can this style not be incorporated into stylesheet?

2023-05-22 15:53 UTC, sweety-sg approved these changes

2023-05-22 15:55 UTC, sweety-sg approved these changes

2023-05-22 15:59 UTC, sweety-sg approved these changes

2023-06-10 08:15 UTC, nikkuAg commented
@bbahd30 
Change every component to Functional based component.

2024-02-14 16:20 UTC, merged